version: "2"

services:
  nginx:
    image: nexus.prod.uci.cu/nginx:alpine
    ports:
      - "80:80"
    volumes: 
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/:/var/www/html/
    links:
      - ghe-tester-fpm:fpm            
    depends_on:
      - ghe-tester-fpm
 
  ghe-tester-fpm:
    image: nexus.prod.uci.cu/ghe_tester/php:7.1-fpm    
    volumes: 
      - ./www/:/var/www/html/:rw
      - ./config/entrypoint.sh:/entrypoint.sh
    links:
      - mysql-db:mysql-db
      - postgres-db:postgres-db
    depends_on:
      - "mysql-db"
      - "postgres-db"
    entrypoint: /bin/bash -c "chown -R www-data:www-data /var/www/html/sites/; /entrypoint.sh"

  phpmyadmin:
    image: nexus.prod.uci.cu/ghe_tester/phpmyadmin    
    environment:
     - MYSQL_ROOT_PASSWORD=ghe     
    restart: always
    ports:
     - 8080:80
    links:
     - mysql-db:db

  phppgadmin:
    image: nexus.prod.uci.cu/ghe_tester/phppgadmin    
    environment:
     - POSTGRES_HOST=db
     - POSTGRES_PORT=5432   
    restart: always
    ports:
     - 8090:80
    links:
     - postgres-db:db

  mysql-db:
    image: nexus.prod.uci.cu/mysql
    volumes: 
      - ./databases/mysql/:/var/lib/mysql  
      # - ./config/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_ROOT_PASSWORD=ghe

  postgres-db:
    image: nexus.prod.uci.cu/postgres:alpine
    volumes: 
      - ./databases/postgres:/var/lib/postgresql/data  
      # - ./config/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=ghe
