version: "2"

services:
  nginx:
    image: nexus.prod.uci.cu/nginx:alpine
    ports:
      - "80:80"
    volumes: 
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/:/var/www/html/
    links:
      - wordpress-fpm:wordpress
      - joomla-fpm:joomla
      - drupal-fpm:drupal
    depends_on:
      - wordpress-fpm
      - joomla-fpm
      - drupal-fpm

  wordpress-fpm:
    image: nexus.prod.uci.cu/wordpress:fpm-alpine
    volumes: 
      - ./www/:/var/www/html/
    links:
      - db:db
    depends_on:
        - "db"

  joomla-fpm:
    image: nexus.prod.uci.cu/joomla:fpm
    volumes: 
      - ./www/:/var/www/html/
    depends_on:
        - "db"
    environment:
      - JOOMLA_DB_HOST=db
      - JOOMLA_DB_USER=root
      - JOOMLA_DB_PASSWORD=ghe
      - JOOMLA_DB_NAME=joomla

  drupal-fpm:
    image: nexus.prod.uci.cu/drupal:fpm
    volumes: 
      - ./www/:/var/www/html/
    links:
      - db:db
    depends_on:
        - "db"

  db:
    image: nexus.prod.uci.cu/mysql
    volumes: 
      - ./mysql/:/var/lib/mysql  
      - ./config/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_ROOT_PASSWORD=ghe
