version: "2"

services:
  nginx:
    image: nexus.prod.uci.cu/nginx:alpine
    ports:
      - "80:80"
    volumes: 
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/:/var/www/html/
    links:
      - ghe-tester-fpm:fpm
            
    depends_on:
      - ghe-tester-fpm
      

  ghe-tester-fpm:
    image: nexus.prod.uci.cu/ghe_tester/php:7.1-fpm
    
    volumes: 
      - ./www/:/var/www/html/:rw
      - ./config/entrypoint.sh:/entrypoint.sh
    links:
      - db:db
    depends_on:
      - "db"
    environment:
      - JOOMLA_DB_HOST=db
      - JOOMLA_DB_USER=root
      - JOOMLA_DB_PASSWORD=ghe
      - JOOMLA_DB_NAME=joomla
    entrypoint: /bin/bash -c "chown -R www-data:www-data /var/www/html/cms/; /entrypoint.sh"

  db:
    image: nexus.prod.uci.cu/mysql
    volumes: 
      - ./mysql/:/var/lib/mysql  
      - ./config/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_ROOT_PASSWORD=ghe
