version: "2"

services:
  nginx:
    image: nexus.prod.uci.cu/nginx:alpine
    ports:
      - "80:80"
    volumes: 
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/:/var/www/html/
    links:
      - wordpress-fpm:wordpress
      - joomla-fpm:joomla
      - drupal-fpm:drupal
      
    depends_on:
      - wordpress-fpm
      - joomla-fpm
      - drupal-fpm
      

  wordpress-fpm:
    image: nexus.prod.uci.cu/wordpress:fpm-alpine
    
    volumes: 
      - ./www/:/var/www/html/:rw
      - ./config/entrypoint.sh:/entrypoint.sh
    links:
      - db:db
    depends_on:
        - "db"
    entrypoint: /bin/bash -c "chown -R www-data:www-data /var/www/html/cms/wordpress; ln -s /var/www/html/ng-filemanager/bridges/php-local /var/www/html/cms/wordpress/php-local ; /entrypoint.sh"


  joomla-fpm:
    image: nexus.prod.uci.cu/joomla:fpm
    volumes: 
      - ./www/:/var/www/html/:rw
      - ./config/entrypoint.sh:/entrypoint.sh
    depends_on:
        - "db"
    environment:
      - JOOMLA_DB_HOST=db
      - JOOMLA_DB_USER=root
      - JOOMLA_DB_PASSWORD=ghe
      - JOOMLA_DB_NAME=joomla
    entrypoint: /bin/bash -c "chown -R www-data:www-data /var/www/html/cms/joomla; ln -s /var/www/html/ng-filemanager/bridges/php-local /var/www/html/cms/joomla/php-local ; /entrypoint.sh"

  drupal-fpm:
    image: nexus.prod.uci.cu/drupal:fpm
    volumes: 
      - ./www/:/var/www/html/:rw
      - ./config/entrypoint.sh:/entrypoint.sh
    links:
      - db:db
    depends_on:
        - "db"
    entrypoint: /bin/bash -c "chown -R www-data:www-data /var/www/html/cms/drupal; ln -s /var/www/html/ng-filemanager/bridges/php-local /var/www/html/cms/drupal/php-local ; /entrypoint.sh"


  db:
    image: nexus.prod.uci.cu/mysql
    volumes: 
      - ./mysql/:/var/lib/mysql  
      - ./config/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_ROOT_PASSWORD=ghe
